sonar.projectKey=cinema_booking_system
sonar.projectName=Cinema Booking System
sonar.projectVersion=1.0
sonar.projectDescription=Casusopdracht Bioscoop - Softwaredesign & -kwaliteit
sonar.organization=avans-2-4

sonar.sources=index/src
sonar.tests=index/src
sonar.inclusions=index/src/**/*.java
sonar.exclusions=index/src/**/*Test.java

sonar.test.inclusions=index/src/**/*Test.java

sonar.java.source=17
sonar.java.target=17
sonar.java.binaries=index/target/classes

sonar.coverage.jacoco.xmlReportPaths=index/target/site/jacoco/jacoco.xml

sonar.testExecutionReportPaths=index/target/surefire-reports

sonar.qualitygate.wait=true

sonar.scm.provider=git
